#!/usr/bin/python3

import sys
import os

try:
    day = int(sys.argv[1])
    star = int(sys.argv[2])
    assert(day in range(1, 26) and star in range(1, 3))
    cmd = f'cd src && g++ -O2 ./day{str(day).zfill(2)}_{str(star)}.cpp && ./a.out'
    print(f'Solving d_{day}_s{star} on `./src/inputs/input{day}.txt`...')
    os.system(cmd) 
except:
    print('Syntax: ./run {day} {star}')
